cc_test(
    name = "test_troika",
    timeout = "short",
    srcs = ["test_troika.c"],
    deps = [
        "@org_iota_common//common/trinary:trit_tryte",
        "//mam/troika",
        "@unity",
    ],
)
