package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pb3",
    srcs = ["pb3.c"],
    hdrs = ["pb3.h"],
    deps = [
        "@org_iota_common//common:errors",
        "@org_iota_common//common/trinary:trit_long",
        "//mam/sponge:spongos",
    ],
)
